//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazarHardamAPI.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazarHardamEntities : DbContext
    {
        public BazarHardamEntities()
            : base("name=BazarHardamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SSL_Address> SSL_Address { get; set; }
        public virtual DbSet<SSL_Authenticate> SSL_Authenticate { get; set; }
        public virtual DbSet<SSL_Brand> SSL_Brand { get; set; }
        public virtual DbSet<SSL_BrandCategory> SSL_BrandCategory { get; set; }
        public virtual DbSet<SSL_CampaignBrand> SSL_CampaignBrand { get; set; }
        public virtual DbSet<SSL_CampaignBrandCategory> SSL_CampaignBrandCategory { get; set; }
        public virtual DbSet<SSL_CampaignProduct> SSL_CampaignProduct { get; set; }
        public virtual DbSet<SSL_CampaignProductCategory> SSL_CampaignProductCategory { get; set; }
        public virtual DbSet<SSL_CampaignSlider> SSL_CampaignSlider { get; set; }
        public virtual DbSet<SSL_Comment> SSL_Comment { get; set; }
        public virtual DbSet<SSL_Coupon> SSL_Coupon { get; set; }
        public virtual DbSet<SSL_DeliveryHistory> SSL_DeliveryHistory { get; set; }
        public virtual DbSet<SSL_DeliveryMan> SSL_DeliveryMan { get; set; }
        public virtual DbSet<SSL_DeliveryType> SSL_DeliveryType { get; set; }
        public virtual DbSet<SSL_Description> SSL_Description { get; set; }
        public virtual DbSet<SSL_Inventory> SSL_Inventory { get; set; }
        public virtual DbSet<SSL_InvStockSummary> SSL_InvStockSummary { get; set; }
        public virtual DbSet<SSL_InvStore> SSL_InvStore { get; set; }
        public virtual DbSet<SSL_Like> SSL_Like { get; set; }
        public virtual DbSet<SSL_OnlineBanking> SSL_OnlineBanking { get; set; }
        public virtual DbSet<SSL_Order> SSL_Order { get; set; }
        public virtual DbSet<SSL_OrderDetail> SSL_OrderDetail { get; set; }
        public virtual DbSet<SSL_OrderStatus> SSL_OrderStatus { get; set; }
        public virtual DbSet<SSL_PaymentHistory> SSL_PaymentHistory { get; set; }
        public virtual DbSet<SSL_PaymentType> SSL_PaymentType { get; set; }
        public virtual DbSet<SSL_Product> SSL_Product { get; set; }
        public virtual DbSet<SSL_ProductCategory> SSL_ProductCategory { get; set; }
        public virtual DbSet<SSL_ProductUnit> SSL_ProductUnit { get; set; }
        public virtual DbSet<SSL_Reference> SSL_Reference { get; set; }
        public virtual DbSet<SSL_ShoppingCart> SSL_ShoppingCart { get; set; }
        public virtual DbSet<SSL_Specification> SSL_Specification { get; set; }
        public virtual DbSet<SSL_User> SSL_User { get; set; }
        public virtual DbSet<SSL_UserBalance> SSL_UserBalance { get; set; }
        public virtual DbSet<SSL_Vendor> SSL_Vendor { get; set; }
    }
}
