//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazarHardamAPI.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSL_Description
    {
        public long Id { get; set; }
        public string LabelName { get; set; }
        public string Description { get; set; }
        public long ProductId { get; set; }
    }
}
