//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazarHardamAPI.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSL_Vendor
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string ContactPerson { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Division { get; set; }
        public string District { get; set; }
        public string PoliceStation { get; set; }
        public string Address { get; set; }
        public string Location { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public string PersonImageName { get; set; }
        public string PersonImagePath { get; set; }
        public string Status { get; set; }
        public string Token { get; set; }
        public System.Guid CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string OCode { get; set; }
    }
}
