//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazarHardamAPI.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSL_InvStockSummary
    {
        public long Id { get; set; }
        public long InvStoreId { get; set; }
        public long ProductId { get; set; }
        public string Barcode { get; set; }
        public decimal ReceivedQty { get; set; }
        public decimal DeliveryQty { get; set; }
        public decimal StoreTransferQty { get; set; }
        public decimal SupplierReturnQty { get; set; }
        public decimal DamageQty { get; set; }
        public decimal SoldQty { get; set; }
        public decimal SalesReturnQty { get; set; }
        public decimal BalanceQty { get; set; }
        public string OCode { get; set; }
    }
}
